# -*- coding: utf-8 -*-
"""NLP_Project_Final_12_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Krb4SIEx-Wvyo3bIGNfp6DZZcxIOzYuW
"""

# ============================================================
# CELL 1: Install + Imports
# ============================================================

!pip install -q --upgrade pip setuptools wheel
!pip install -q \
    "transformers>=4.40.0" \
    "accelerate>=0.30.0" \
    "tokenizers>=0.19.0" \
    datasets \
    kagglehub \
    seaborn

import os, glob, re, random, json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import torch
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    get_linear_schedule_with_warmup,
)

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    confusion_matrix,
    classification_report,
)

import kagglehub

print("✔ All libraries imported successfully!")
print("Torch version:", torch.__version__)
print("Transformers version:", __import__('transformers').__version__)
print("CUDA available:", torch.cuda.is_available())

# ============================================================
# CELL 2: Configuration & Reproducibility (5-class, V1 only)
# ============================================================

MODEL_NAME = "roberta-base"

# Hyperparameters
MAX_LENGTH = 384
BATCH_SIZE = 8
GRAD_ACCUM_STEPS = 2
NUM_EPOCHS = 16
EARLY_STOPPING_PATIENCE = 3
LR = 1e-5
WARMUP_RATIO = 0.10
WEIGHT_DECAY = 0.01
LABEL_SMOOTH = 0.03

VAL_SIZE = 0.15
TEST_SIZE = 0.15
RANDOM_SEED = 42

# Columns in Kaggle data
TEXT_COLUMN = "text"
TITLE_COLUMN = "title"
RAW_LABEL_COLUMN = "target"   # Kaggle label 0–4

# Canonical 5-class labels (Stress → None)
CANON_LABELS = {
    "None": 0,
    "Depression": 1,
    "Bipolar disorder": 2,
    "Personality disorder": 3,
    "Anxiety": 4,
}
ID2LABEL_CANON = {v: k for k, v in CANON_LABELS.items()}
LABEL2ID_CANON = {k: v for k, v in CANON_LABELS.items()}

# Lowercase names for HF model head
id2label_hf = {
    0: "none",
    1: "depression",
    2: "bipolar disorder",
    3: "personality disorder",
    4: "anxiety",
}
label2id_hf = {v: k for k, v in id2label_hf.items()}


def set_seed(seed=RANDOM_SEED):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False


set_seed()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)
print("TEXT_COLUMN:", TEXT_COLUMN)
print("RAW_LABEL_COLUMN:", RAW_LABEL_COLUMN)
print(f"MAX_LENGTH: {MAX_LENGTH}, LR: {LR}, EPOCHS: {NUM_EPOCHS}, BATCH_SIZE: {BATCH_SIZE}")
print("GRAD_ACCUM_STEPS:", GRAD_ACCUM_STEPS)

# ============================================================
# CELL 3: Load Kaggle Dataset & Combine Title+Text
# ============================================================

root_path = kagglehub.dataset_download("neelghoshal/reddit-mental-health-data")
print("📁 Dataset root path:", root_path)

preferred = os.path.join(root_path, "data_to_be_cleansed.csv")
RAW_CSV_PATH = preferred if os.path.exists(preferred) else glob.glob(os.path.join(root_path, "*.csv"))[0]
print("📄 Using CSV:", RAW_CSV_PATH)

df = pd.read_csv(RAW_CSV_PATH)
pd.set_option("display.max_colwidth", 200)
print("✅ Raw shape:", df.shape)
display(df.head())

# Drop index-like column if present
df = df.drop(columns=["Unnamed: 0"], errors="ignore")

# Ensure title + text exist
df[TITLE_COLUMN] = df.get(TITLE_COLUMN, "").fillna("").astype(str)
df[TEXT_COLUMN]  = df.get(TEXT_COLUMN, "").fillna("").astype(str)

# Combine title + text
df["text_full"] = (df[TITLE_COLUMN] + " " + df[TEXT_COLUMN]).str.strip()

print("\nColumns:", df.columns.tolist())
print("Example combined text_full:")
display(df[[TITLE_COLUMN, TEXT_COLUMN, "text_full"]].head())

# ============================================================
# CELL 4: Cleaning (match teammate's clean_for_bert style)
# ============================================================

CLEAN_CFG = dict(
    lower=True,
    strip_html=True,
    strip_md=True,
    strip_urls=True,
    squash_spaces=True,
    min_chars=5,
)

html_tag_re = re.compile(r"<.*?>")
md_link_re  = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
url_re      = re.compile(r"http\S+|www\.\S+")
word_re     = re.compile(r"\b\w+\b")


def clean_for_bert(s: str) -> str:
    s = str(s)
    if CLEAN_CFG["lower"]:
        s = s.lower()
    if CLEAN_CFG["strip_html"]:
        s = html_tag_re.sub(" ", s)
    if CLEAN_CFG["strip_md"]:
        s = md_link_re.sub(r"\1", s)
    if CLEAN_CFG["strip_urls"]:
        s = url_re.sub(" ", s)
    if CLEAN_CFG["squash_spaces"]:
        s = " ".join(s.split())
    return s


def word_count(s: str) -> int:
    return len(word_re.findall(str(s)))


# Pre-clean EDA (optional)
df["_char_len_raw"] = df["text_full"].map(lambda s: len(str(s)))
df["_word_len_raw"] = df["text_full"].map(word_count)

print("=== Character length (raw) ===")
display(df["_char_len_raw"].describe().to_frame("char_len_raw"))
print("\n=== Word length (raw) ===")
display(df["_word_len_raw"].describe().to_frame("word_len_raw"))

plt.figure(figsize=(6, 4))
df["_word_len_raw"].hist(bins=60, edgecolor="black")
plt.title("Word Count Distribution (raw)")
plt.xlabel("# words")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

# Apply cleaning
df["text_clean"] = df["text_full"].map(clean_for_bert)
before = len(df)
df = df[df["text_clean"].str.len() >= CLEAN_CFG["min_chars"]].reset_index(drop=True)
print(f"🧹 Removed {before-len(df)} very short rows. Remaining: {len(df)}")

# Post-clean EDA
df["_char_len_clean"] = df["text_clean"].map(len)
df["_word_len_clean"] = df["text_clean"].map(word_count)

print("\n=== Character length (clean) ===")
display(df["_char_len_clean"].describe().to_frame("char_len_clean"))
print("\n=== Word length (clean) ===")
display(df["_word_len_clean"].describe().to_frame("word_len_clean"))

plt.figure(figsize=(6, 4))
df["_word_len_clean"].hist(bins=60, edgecolor="black")
plt.title("Word Count Distribution (cleaned)")
plt.xlabel("# words")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

# ============================================================
# CELL 5: Label Normalization (5 classes: None, Dep, Bipolar, Pers, Anxiety)
# ============================================================

label_col = RAW_LABEL_COLUMN
print("✅ Using label column:", label_col)

# Keep original label as string for debugging
df["raw_label"] = df[label_col].astype(str)


def normalize_label(x):
    s = str(x).strip().lower()

    # numeric mapping 0–4 (from Kaggle)
    if s.isdigit():
        code = int(s)
        if code == 0:
            # Stress → map to None (0)
            return CANON_LABELS["None"]
        if code == 1:
            return CANON_LABELS["Depression"]
        if code == 2:
            return CANON_LABELS["Bipolar disorder"]
        if code == 3:
            return CANON_LABELS["Personality disorder"]
        if code == 4:
            return CANON_LABELS["Anxiety"]

    # textual fallback (if ever present)
    if "stress" in s:
        return CANON_LABELS["None"]
    if "depression" in s or "depressed" in s:
        return CANON_LABELS["Depression"]
    if "bipolar" in s or "manic" in s:
        return CANON_LABELS["Bipolar disorder"]
    if "personality" in s or s in {"bpd", "npd", "pd"}:
        return CANON_LABELS["Personality disorder"]
    if "anxiety" in s or "anxious" in s:
        return CANON_LABELS["Anxiety"]

    return None


df["label_id"] = df["raw_label"].map(normalize_label)

before_map = len(df)
df = df.dropna(subset=["label_id"]).reset_index(drop=True)
df["label_id"] = df["label_id"].astype(int)
after_map = len(df)

print(f"🧹 Removed {before_map-after_map} rows with unmapped labels.")
print("✅ Remaining rows:", len(df))

print("\n=== Label distribution (canonical, 5 classes) ===")
label_counts = df["label_id"].map(ID2LABEL_CANON).value_counts()
display(label_counts.to_frame("count"))

plt.figure(figsize=(6, 4))
label_counts.plot(kind="bar", edgecolor="black")
plt.title("Label Distribution (5 classes, Stress→None)")
plt.xlabel("Label")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

# ============================================================
# CELL 6: Token Length Filtering (use public tokenizer)
# ============================================================

len_tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)

print("🔁 Calculating token lengths with roberta-base tokenizer…")
df["_tok_len_pre_filter"] = df["text_clean"].map(
    lambda x: len(len_tokenizer(x, add_special_tokens=True)["input_ids"])
)

print("\n=== Token length stats (clean, pre-filter) ===")
display(df["_tok_len_pre_filter"].describe().to_frame("token_len"))

plt.figure(figsize=(6, 4))
df["_tok_len_pre_filter"].hist(bins=60, edgecolor="black")
plt.axvline(512, linestyle="--", label="512-token cutoff")
plt.title("Token Length Distribution (cleaned)")
plt.xlabel("# tokens")
plt.ylabel("Frequency")
plt.legend()
plt.tight_layout()
plt.show()

before_len = len(df)
df = df[df["_tok_len_pre_filter"] <= 512].reset_index(drop=True)
after_len = len(df)
print(f"✂️ Dropped {before_len-after_len} rows > 512 tokens. Remaining: {after_len}")

# ============================================================
# CELL 7: Duplicate & Conflict Removal
# ============================================================

print("\n=== DUPLICATE ANALYSIS ===")
print("Duplicates before cleaning:", df.duplicated(subset=["text_clean"]).sum())

dup_mask = df.duplicated(subset=["text_clean"], keep=False)
df_dups = df[dup_mask].copy()
print("Total duplicated rows:", len(df_dups))

# Group duplicates, look for conflicting labels
grouped = df_dups.groupby("text_clean").agg({
    "label_id": lambda x: list(x),
    "raw_label": lambda x: list(x),
})

conflicting_mask = grouped["label_id"].apply(lambda labels: len(set(labels)) > 1)
high_risk = grouped[conflicting_mask]

print("\n❗ High-risk conflicting groups:", len(high_risk))
display(high_risk.head(10))

# Remove all texts that appear with conflicting labels
conflicting_texts = set(high_risk.index)

before_conf = len(df)
df_no_conflicts = df[~df["text_clean"].isin(conflicting_texts)].copy()
after_conf = len(df_no_conflicts)
print(f"\nRemoved {before_conf-after_conf} rows belonging to conflicting groups.")
print("Shape after removing conflicts:", df_no_conflicts.shape)

# Remove remaining duplicates (same text, same label, keep first)
before_dups = len(df_no_conflicts)
df_final = df_no_conflicts.drop_duplicates(subset=["text_clean"], keep="first").reset_index(drop=True)
after_dups = len(df_final)
print(f"Removed {before_dups-after_dups} additional duplicate rows.")
print("✅ Final dataset WITHOUT ANY duplicates:", df_final.shape)

print("\nRemaining duplicates:", df_final.duplicated(subset=["text_clean"]).sum())

print("\n=== Final Label Distribution (5-class, Stress→None) ===")
final_counts = df_final["label_id"].map(ID2LABEL_CANON).value_counts()
display(final_counts.to_frame("count"))

plt.figure(figsize=(6, 4))
final_counts.plot(kind="bar", edgecolor="black")
plt.title("Label Distribution (Final Deduped Dataset)")
plt.xlabel("Label")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

df_clean = df_final.copy()
print("📌 FINAL CLEAN DATASET SHAPE:", df_clean.shape)
display(df_clean.head())

# ============================================================
# CELL 8: Train / Val / Test Split (stratified 70/15/15)
# ============================================================

X = df_clean["text_clean"].astype(str).values
y = df_clean["label_id"].astype(int).values

print("Total samples:", len(X))

# First split: test set
X_train_val, X_test, y_train_val, y_test = train_test_split(
    X, y,
    test_size=TEST_SIZE,
    stratify=y,
    random_state=RANDOM_SEED,
)

# Second split: validation from train_val
val_relative_size = VAL_SIZE / (1.0 - TEST_SIZE)

X_train, X_val, y_train, y_val = train_test_split(
    X_train_val, y_train_val,
    test_size=val_relative_size,
    stratify=y_train_val,
    random_state=RANDOM_SEED,
)

print(f"Train: {len(X_train)} ({len(X_train)/len(X)*100:.1f}%)")
print(f"Val:   {len(X_val)} ({len(X_val)/len(X)*100:.1f}%)")
print(f"Test:  {len(X_test)} ({len(X_test)/len(X)*100:.1f}%)")


def show_dist(name, labels):
    print(f"\n{name} distribution:")
    unique, counts = np.unique(labels, return_counts=True)
    for label_id, cnt in zip(unique, counts):
        label_name = ID2LABEL_CANON[label_id]
        pct = cnt / len(labels) * 100
        print(f"  {label_id} ({label_name}): {cnt} ({pct:.1f}%)")


show_dist("TRAIN", y_train)
show_dist("VAL",   y_val)
show_dist("TEST",  y_test)

# --------- CLASS WEIGHTS (inverse frequency on TRAIN) ----------
unique, counts = np.unique(y_train, return_counts=True)
freqs = counts / counts.sum()
inv_freq = 1.0 / freqs
class_weights = inv_freq / inv_freq.mean()   # normalize around 1.0

CLASS_WEIGHTS = torch.tensor(class_weights, dtype=torch.float32, device=device)

print("\n📊 Class weights (inverse frequency, TRAIN):")
for i, w in enumerate(class_weights):
    print(f"  {i} ({ID2LABEL_CANON[i]}): weight={w:.3f}")

# ============================================================
# CELL 9: Tokenizer & Dataset Class for RoBERTa
# ============================================================

roberta_tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)


class MentalHealthDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=MAX_LENGTH):
        self.texts = list(texts)
        self.labels = list(labels)
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = str(self.texts[idx])
        label = int(self.labels[idx])

        encoding = self.tokenizer(
            text,
            truncation=True,
            padding="max_length",
            max_length=self.max_length,
            return_tensors="pt",
        )
        item = {k: v.squeeze(0) for k, v in encoding.items()}
        item["labels"] = torch.tensor(label, dtype=torch.long)
        return item


train_dataset = MentalHealthDataset(X_train, y_train, roberta_tokenizer, MAX_LENGTH)
val_dataset   = MentalHealthDataset(X_val,   y_val,   roberta_tokenizer, MAX_LENGTH)
test_dataset  = MentalHealthDataset(X_test,  y_test,  roberta_tokenizer, MAX_LENGTH)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False)
test_loader  = DataLoader(test_dataset,  batch_size=BATCH_SIZE, shuffle=False)

print("Dataloaders ready!")

# ============================================================
# CELL 10: Model Factory (V1 – full fine-tuning only)
# ============================================================

def create_roberta_model(num_labels):
    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=num_labels,
        id2label=id2label_hf,
        label2id=label2id_hf,
    )

     # ADD REGULARIZATION
    model.config.hidden_dropout_prob = 0.2
    model.config.attention_probs_dropout_prob = 0.2

    # All layers trainable (full fine-tuning)
    print("🔓 Full fine-tuning: all RoBERTa layers + classifier trainable.")
    return model.to(device)

# ============================================================
# CELL 11: Training & Evaluation Helpers (Optimized + Early Stopping)
# ============================================================

def train_one_model(
    model,
    train_loader,
    val_loader,
    num_epochs=NUM_EPOCHS,
    lr=LR,
):
    # Weighted + smoothed loss
    loss_fn = torch.nn.CrossEntropyLoss(
        weight=CLASS_WEIGHTS,
        label_smoothing=LABEL_SMOOTH,
    )

    optimizer = AdamW(
        filter(lambda p: p.requires_grad, model.parameters()),
        lr=lr,
        weight_decay=WEIGHT_DECAY,
    )

    total_steps = (len(train_loader) // GRAD_ACCUM_STEPS) * num_epochs
    warmup_steps = int(WARMUP_RATIO * total_steps)

    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=warmup_steps,
        num_training_steps=total_steps,
    )

    history = {"train_loss": [], "val_loss": []}

    best_val_loss = float("inf")
    patience_counter = 0

    print(
        f"\n🔥 Training: epochs={num_epochs}, lr={lr}, "
        f"batch_size={BATCH_SIZE}, grad_accum={GRAD_ACCUM_STEPS}, "
        f"warmup_ratio={WARMUP_RATIO}, wd={WEIGHT_DECAY}"
    )

    model.to(device)

    for epoch in range(num_epochs):
        # ---- TRAIN ----
        model.train()
        total_train_loss = 0.0
        optimizer.zero_grad()

        for step, batch in enumerate(train_loader):
            batch = {k: v.to(device) for k, v in batch.items()}
            labels = batch["labels"]

            outputs = model(**batch)
            logits = outputs.logits

            loss = loss_fn(logits, labels)
            loss = loss / GRAD_ACCUM_STEPS
            loss.backward()

            if (step + 1) % GRAD_ACCUM_STEPS == 0:
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
                scheduler.step()
                optimizer.zero_grad()

            total_train_loss += loss.item() * GRAD_ACCUM_STEPS

        avg_train_loss = total_train_loss / len(train_loader)

        # ---- VALIDATION ----
        model.eval()
        total_val_loss = 0.0
        with torch.no_grad():
            for batch in val_loader:
                batch = {k: v.to(device) for k, v in batch.items()}
                labels = batch["labels"]
                outputs = model(**batch)
                logits = outputs.logits
                val_loss = loss_fn(logits, labels)
                total_val_loss += val_loss.item()

        avg_val_loss = total_val_loss / len(val_loader)

        history["train_loss"].append(avg_train_loss)
        history["val_loss"].append(avg_val_loss)

        print(
            f"Epoch {epoch+1}/{num_epochs} | "
            f"Train Loss: {avg_train_loss:.4f} | "
            f"Val Loss: {avg_val_loss:.4f}"
        )

        # ---- EARLY STOPPING ----
        if avg_val_loss < best_val_loss:
            best_val_loss = avg_val_loss
            patience_counter = 0
            torch.save(model.state_dict(), "best_model_v1.pt")
        else:
            patience_counter += 1
            if patience_counter >= EARLY_STOPPING_PATIENCE:
                print(f"⛔ Early stopping triggered at epoch {epoch+1}")
                break

    # Load best checkpoint
    model.load_state_dict(torch.load("best_model_v1.pt", map_location=device))
    print("✔ Loaded best checkpoint for Version 1")
    print("🔥 Training finished!")
    return model, history


def evaluate_model(model, data_loader, label_names=None):
    model.eval()
    all_labels = []
    all_preds = []

    with torch.no_grad():
        for batch in data_loader:
            labels = batch["labels"].numpy()
            batch = {k: v.to(device) for k, v in batch.items()}
            outputs = model(**batch)
            logits = outputs.logits.detach().cpu().numpy()
            preds = np.argmax(logits, axis=1)

            all_labels.extend(labels)
            all_preds.extend(preds)

    all_labels = np.array(all_labels)
    all_preds  = np.array(all_preds)

    acc = accuracy_score(all_labels, all_preds)
    precision, recall, f1, _ = precision_recall_fscore_support(
        all_labels,
        all_preds,
        average="macro",
        zero_division=0,
    )

    print(f"Accuracy:       {acc:.4f}")
    print(f"Macro Precision:{precision:.4f}")
    print(f"Macro Recall:   {recall:.4f}")
    print(f"Macro F1:       {f1:.4f}")

    print("\nClassification report:")
    print(classification_report(all_labels, all_preds, target_names=label_names))

    cm = confusion_matrix(all_labels, all_preds)
    return {
        "accuracy": acc,
        "macro_precision": precision,
        "macro_recall": recall,
        "macro_f1": f1,
        "confusion_matrix": cm,
        "true_labels": all_labels,
        "pred_labels": all_preds,
    }


def plot_loss_curves(history, title="Loss Curves"):
    plt.figure(figsize=(6, 4))
    plt.plot(history["train_loss"], label="Train Loss")
    plt.plot(history["val_loss"],   label="Val Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title(title)
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()


def plot_confusion_matrix_counts(cm, label_names, title="Confusion Matrix (Counts)"):
    plt.figure(figsize=(6, 5))
    sns.heatmap(
        cm,
        annot=True,
        fmt="d",
        xticklabels=label_names,
        yticklabels=label_names,
        cmap="Blues",
    )
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.title(title)
    plt.tight_layout()
    plt.show()

def plot_confusion_matrix_percent(cm, label_names, title="Confusion Matrix (Percentages)"):
    cm_percent = cm / cm.sum(axis=1, keepdims=True) * 100

    # Create annotation labels like "81%"
    annot_labels = np.array([[f"{v:.0f}%" for v in row] for row in cm_percent])

    plt.figure(figsize=(6, 5))
    sns.heatmap(
        cm_percent,
        annot=annot_labels,     # <-- use preformatted strings
        fmt="",
        xticklabels=label_names,
        yticklabels=label_names,
        cmap="YlGnBu",
    )
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.title(title)
    plt.tight_layout()
    plt.show()

# ============================================================
# CELL 12: Version 1 – General RoBERTa (full fine-tuning)
# ============================================================

label_list = [id2label_hf[i] for i in range(len(id2label_hf))]

print("=== Version 1: General RoBERTa-base (full fine-tuning) ===")
set_seed()

model_v1 = create_roberta_model(
    num_labels=len(id2label_hf),
)

# Optional: enable gradient checkpointing to save memory
model_v1.gradient_checkpointing_enable()

model_v1, history_v1 = train_one_model(
    model_v1,
    train_loader,
    val_loader,
    num_epochs=NUM_EPOCHS,
    lr=LR,
)

plot_loss_curves(history_v1, title="Version 1 – General RoBERTa: Loss Curves")

print("\n--- Test evaluation: Version 1 ---")
results_v1 = evaluate_model(model_v1, test_loader, label_names=label_list)

# Confusion Matrices
plot_confusion_matrix_counts(
    results_v1["confusion_matrix"],
    label_list,
    title="Version 1 – Confusion Matrix (Counts)"
)

plot_confusion_matrix_percent(
    results_v1["confusion_matrix"],
    label_list,
    title="Version 1 – Confusion Matrix (Percentages)"
)

def plot_confusion_matrix_percent(cm, label_names, title="Confusion Matrix (Percentages)"):
    cm_percent = cm / cm.sum(axis=1, keepdims=True) * 100

    # Create annotation labels like "81%"
    annot_labels = np.array([[f"{v:.0f}%" for v in row] for row in cm_percent])

    plt.figure(figsize=(6, 5))
    sns.heatmap(
        cm_percent,
        annot=annot_labels,     # <-- use preformatted strings
        fmt="",
        xticklabels=label_names,
        yticklabels=label_names,
        cmap="Greens",
    )
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.title(title)
    plt.tight_layout()
    plt.show()

plot_confusion_matrix_percent(
    results_v1["confusion_matrix"],
    label_list,
    title="Version 1 – Confusion Matrix (Percentages)"
)

# ============================================================
# CELL 13: Class-wise F1 Bar Chart (Version 1)
# ============================================================

report_v1 = classification_report(
    results_v1["true_labels"],
    results_v1["pred_labels"],
    output_dict=True,
    zero_division=0
)

classes_order = [0, 1, 2, 3, 4]
f1_scores = [report_v1[str(i)]["f1-score"] for i in classes_order]

f1_df = pd.DataFrame({
    "Class": [ID2LABEL_CANON[i] for i in classes_order],
    "F1": f1_scores,
})

plt.figure(figsize=(8, 5))
plt.bar(f1_df["Class"], f1_df["F1"])
plt.title("Class-wise F1 Score – Version 1 (General RoBERTa)")
plt.ylabel("F1 Score")
plt.xlabel("Mental Health Condition")
plt.ylim(0, 1.0)
plt.grid(axis="y")
plt.tight_layout()
plt.show()

display(f1_df)

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report
import numpy as np

# Generate classification report
report_v1 = classification_report(
    results_v1["true_labels"],
    results_v1["pred_labels"],
    output_dict=True,
    zero_division=0
)

classes_order = [0, 1, 2, 3, 4]

# Extract all metrics for each class
metrics_data = {
    "Class": [ID2LABEL_CANON[i] for i in classes_order],
    "Precision": [report_v1[str(i)]["precision"] for i in classes_order],
    "Recall": [report_v1[str(i)]["recall"] for i in classes_order],
    "F1": [report_v1[str(i)]["f1-score"] for i in classes_order],
}

metrics_df = pd.DataFrame(metrics_data)

# Calculate per-class accuracy (TP / total samples in that class)
accuracy_per_class = []
for i in classes_order:
    class_mask = results_v1["true_labels"] == i
    if class_mask.sum() > 0:
        correct = (results_v1["true_labels"][class_mask] == results_v1["pred_labels"][class_mask]).sum()
        accuracy = correct / class_mask.sum()
    else:
        accuracy = 0
    accuracy_per_class.append(accuracy)

metrics_df["Accuracy"] = accuracy_per_class

# Display the dataframe
print("Class-wise Metrics Summary – Version 1")
print(metrics_df)
print()

# Create a 2x2 subplot grid for individual metrics
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle("Class-wise Performance Metrics – Version 1 (General RoBERTa)", fontsize=14, fontweight="bold")

metrics = ["Precision", "Recall", "F1", "Accuracy"]
colors = ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728"]

for idx, (ax, metric, color) in enumerate(zip(axes.flat, metrics, colors)):
    values = metrics_df[metric].values
    max_val = values.max()

    # Highlight only the highest bar
    bar_colors = [color if v == max_val else "#cccccc" for v in values]

    ax.bar(metrics_df["Class"], values, color=bar_colors, edgecolor="black", linewidth=1.5)
    ax.set_ylabel(metric, fontsize=11, fontweight="bold")
    ax.set_title(f"{metric} by Class", fontsize=12, fontweight="bold")
    ax.set_ylim(0, 1.0)
    ax.grid(axis="y", alpha=0.3)
    ax.tick_params(axis="x", rotation=45)

plt.tight_layout()
plt.show()

# Create a grouped bar chart for all metrics
fig, ax = plt.subplots(figsize=(12, 6))

x = np.arange(len(metrics_df))
width = 0.2
metric_list = ["Precision", "Recall", "F1", "Accuracy"]
metric_colors = ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728"]

for idx, metric in enumerate(metric_list):
    offset = width * (idx - 1.5)
    values = metrics_df[metric].values
    max_idx = np.argmax(values)

    # Highlight only the highest bar for each metric
    bar_colors = [metric_colors[idx] if i == max_idx else "#cccccc" for i in range(len(values))]

    ax.bar(x + offset, values, width, label=metric, alpha=0.8, edgecolor="black", linewidth=1.2)

ax.set_xlabel("Mental Health Condition", fontsize=11, fontweight="bold")
ax.set_ylabel("Score", fontsize=11, fontweight="bold")
ax.set_title("Class-wise Metrics Comparison – Version 1", fontsize=13, fontweight="bold")
ax.set_xticks(x)
ax.set_xticklabels(metrics_df["Class"])
ax.legend(fontsize=10)
ax.set_ylim(0, 1.0)
ax.grid(axis="y", alpha=0.3)
plt.tight_layout()
plt.show()

# Display metrics dataframe
display(metrics_df)

# ============================================================
# COMPLETE MENTAL HEALTH CLASSIFICATION PIPELINE
# Combined: Training (V1) + Hybrid Sample Testing
# ============================================================

# CELLS 1-13: Training Pipeline (unchanged)
# [Insert your existing CELLS 1-13 here - they remain the same]

# ============================================================
# CELL 14: HYBRID SAMPLE TESTING (New Section)
# ============================================================
# Uses REAL "None" samples from test set + Curated Reddit-style samples
# for mental health classes - best of both worlds!
# ============================================================

print("\n" + "="*70)
print("HYBRID SAMPLE TESTING: REAL 'NONE' + CURATED MENTAL HEALTH")
print("="*70)

# ---- Extract Real "None" Samples from Test Set ----
print("\n📋 Extracting 'None' samples from test set...")
none_class_id = LABEL2ID_CANON["None"]
none_indices = np.where(y_test == none_class_id)[0]

np.random.seed(42)
if len(none_indices) >= 10:
    selected_none_indices = np.random.choice(none_indices, size=10, replace=False)
else:
    selected_none_indices = none_indices

NONE_SAMPLES = [X_test[i] for i in selected_none_indices]
print(f"✅ Selected {len(NONE_SAMPLES)} 'None' samples from test set")

# ---- Curated Reddit-Style Mental Health Samples (10 each) ----

DEPRESSION_SAMPLES = [
    "I can't remember the last time I felt genuinely happy. Everything just feels gray and pointless.",
    "Been in bed for 3 days straight. I know I should shower and eat but I just can't find the energy.",
    "I feel like I'm drowning and everyone around me is breathing just fine. Why is it so hard for me?",
    "Nothing brings me joy anymore. Not my hobbies, not my friends, nothing. I'm just going through the motions.",
    "I cry every single day and I don't even know why anymore. It's exhausting.",
    "My family tells me to 'just be happy' but they don't understand that I can't just snap out of this.",
    "Is it normal to feel empty all the time? Like there's a void inside that nothing can fill?",
    "I used to love painting but now I can't even pick up a brush. I've lost interest in everything.",
    "Sleeping 14 hours a day and still feeling exhausted. What's wrong with me?",
    "I canceled plans with friends again. I just can't bring myself to socialize anymore.",
]

BIPOLAR_SAMPLES = [
    "I haven't slept in 4 days and I feel AMAZING! So much energy! Started 3 new projects!",
    "Last week I was on top of the world, today I can't even get out of bed. This rollercoaster is killing me.",
    "My mind is racing so fast I can't keep up with my own thoughts. Is this normal?",
    "I spent $3000 on things I don't need during a manic episode and now I'm broke and depressed about it.",
    "One minute I'm euphoric and invincible, the next I'm crying on the floor. I hate this so much.",
    "I was so productive yesterday, worked 18 hours straight. Today I feel like I'm dying and everything seems pointless.",
    "My family says I'm 'too much' when I'm up and 'too distant' when I'm down. I can't win.",
    "The crash after a manic episode is the worst feeling. Going from feeling invincible to feeling worthless.",
    "I have so many unfinished projects from my manic phases. My room is full of half-done things.",
    "My mood swings are so extreme that I don't even recognize myself sometimes.",
]

PERSONALITY_DISORDER_SAMPLES = [
    "My boyfriend didn't text me back for 2 hours and now I'm convinced he hates me and wants to break up.",
    "I don't know who I am anymore. My personality seems to change depending on who I'm with.",
    "I go from loving someone to hating them in seconds. My emotions are so intense and unstable.",
    "I have this overwhelming fear of abandonment that controls my life. I push people away before they can leave me.",
    "I feel empty inside all the time. Like there's nothing at the core of who I am.",
    "My relationships are always intense and chaotic. I idealize people then suddenly see them as terrible.",
    "I have such an unstable sense of self. Yesterday I wanted to be a writer, today I want to drop everything.",
    "My mood can change drastically within hours. People say I'm unpredictable.",
    "I split on people constantly - they're either perfect or terrible, no in-between.",
    "I'm terrified of being alone but I also push everyone away. I don't understand myself.",
]

ANXIETY_SAMPLES = [
    "My heart is racing for no reason and I can't calm down. What if something bad is about to happen?",
    "I've been having panic attacks almost daily. My chest gets tight and I feel like I can't breathe.",
    "I'm so worried about everything all the time. What if I lose my job? What if I get sick?",
    "I had to leave the grocery store because I started having a panic attack. Too many people.",
    "I can't stop thinking about all the things that could go wrong. My mind won't shut off.",
    "I've been having intrusive thoughts that keep me up at night. The constant worry is exhausting.",
    "Social situations make me so anxious that I avoid them completely. I'm lonely but terrified of interaction.",
    "I replay conversations in my head over and over, analyzing every word I said. Did I say something wrong?",
    "I catastrophize everything. If my boss wants to talk to me, I immediately think I'm getting fired.",
    "I check the locks on my doors multiple times before bed because I'm anxious about safety.",
]

# ---- Combine All Samples ----
all_samples = []

for text in NONE_SAMPLES:
    all_samples.append({"text": text, "true_label": "None"})

for text in DEPRESSION_SAMPLES:
    all_samples.append({"text": text, "true_label": "Depression"})

for text in BIPOLAR_SAMPLES:
    all_samples.append({"text": text, "true_label": "Bipolar disorder"})

for text in PERSONALITY_DISORDER_SAMPLES:
    all_samples.append({"text": text, "true_label": "Personality disorder"})

for text in ANXIETY_SAMPLES:
    all_samples.append({"text": text, "true_label": "Anxiety"})

print(f"\n✅ Total samples loaded: {len(all_samples)}")
print(f"   - None: {len(NONE_SAMPLES)}")
print(f"   - Depression: {len(DEPRESSION_SAMPLES)}")
print(f"   - Bipolar disorder: {len(BIPOLAR_SAMPLES)}")
print(f"   - Personality Disorder: {len(PERSONALITY_DISORDER_SAMPLES)}")
print(f"   - Anxiety: {len(ANXIETY_SAMPLES)}")

# ---- Make Predictions on Hybrid Samples ----
print("\n🔮 Making predictions on all hybrid samples...")

texts = [s["text"] for s in all_samples]
true_labels = [s["true_label"] for s in all_samples]

# Tokenize
encodings = roberta_tokenizer(
    texts,
    padding=True,
    truncation=True,
    max_length=MAX_LENGTH,
    return_tensors="pt"
)

# Move to device and predict
encodings = {k: v.to(device) for k, v in encodings.items()}

with torch.no_grad():
    outputs = model_v1(**encodings)
    logits = outputs.logits
    pred_ids = torch.argmax(logits, dim=-1).cpu().numpy()

# Convert predictions to label names
pred_labels = [ID2LABEL_CANON[pred_id] for pred_id in pred_ids]

print("✅ Predictions complete!")

# ---- Create Visualization DataFrame ----
print("\n📊 Creating results dataframe...")

viz_data = []
for i, (text, true_label, pred_label) in enumerate(zip(texts, true_labels, pred_labels)):
    display_text = text[:300] + "..." if len(text) > 300 else text
    viz_data.append({
        "Sample_Num": i + 1,
        "True_Label": true_label,
        "Predicted_Label": pred_label,
        "Text": display_text,
        "Correct": true_label == pred_label,
        "Full_Text": text
    })

viz_df = pd.DataFrame(viz_data)
viz_df.to_csv("hybrid_sample_predictions.csv", index=False)
print(f"✅ Saved predictions to: hybrid_sample_predictions.csv")

# ---- Statistics by Class ----
print("\n" + "="*70)
print("PREDICTION STATISTICS BY CLASS")
print("="*70)

class_order = ["None", "Depression", "Bipolar disorder", "Personality disorder", "Anxiety"]

for class_name in class_order:
    class_df = viz_df[viz_df["True_Label"] == class_name]

    if len(class_df) == 0:
        continue

    correct = class_df["Correct"].sum()
    total = len(class_df)
    accuracy = (correct / total * 100) if total > 0 else 0

    print(f"\n{class_name}:")
    print(f"   Total samples: {total}")
    print(f"   Correct: {correct}/{total} ({accuracy:.1f}%)")

    if correct < total:
        wrong_df = class_df[~class_df["Correct"]]
        misclass_counts = wrong_df["Predicted_Label"].value_counts()
        if len(misclass_counts) > 0:
            print(f"   Common misclassifications:")
            for pred_label, count in misclass_counts.head(3).items():
                print(f"      → {pred_label}: {count} samples")

overall_acc = viz_df["Correct"].mean() * 100
print(f"\n📊 Overall accuracy on hybrid samples: {overall_acc:.1f}%")

# ---- Confusion Matrix ----
y_true = [LABEL2ID_CANON[label] for label in true_labels]
y_pred = pred_ids

cm = confusion_matrix(y_true, y_pred)
cm_percent = cm.astype("float") / cm.sum(axis=1)[:, np.newaxis] * 100

print("\n📊 Confusion Matrix (Percentages):")
print(cm_percent.round(1))

print("\n📊 Classification Report:")
report = classification_report(
    y_true,
    y_pred,
    target_names=class_order,
    digits=4
)
print(report)

# ---- Summary Table ----
print("\n" + "="*70)
print("FINAL SUMMARY TABLE")
print("="*70)

summary_data = []
for class_name in class_order:
    class_df = viz_df[viz_df["True_Label"] == class_name]

    if len(class_df) == 0:
        continue

    correct = class_df["Correct"].sum()
    total = len(class_df)
    accuracy = (correct / total * 100) if total > 0 else 0

    summary_data.append({
        "Class": class_name,
        "Total Samples": total,
        "Correct": correct,
        "Incorrect": total - correct,
        "Accuracy (%)": f"{accuracy:.1f}"
    })

summary_df = pd.DataFrame(summary_data)
print("\n" + summary_df.to_string(index=False))

print("\n" + "="*70)
print("HYBRID SAMPLE TESTING COMPLETE!")
print("="*70)
print(f"\n📁 CSV file saved: hybrid_sample_predictions.csv")
print(f"📊 Total samples tested: {len(viz_df)}")
print(f"🎯 Overall accuracy: {overall_acc:.1f}%")
print(f"🏆 Model tested: Version 1 (General RoBERTa-base)")

import pandas as pd
import numpy as np
from IPython.display import display, HTML
from sklearn.metrics import confusion_matrix, classification_report

print("\n" + "="*70)
print("HYBRID SAMPLE TESTING: REAL 'NONE' + CURATED MENTAL HEALTH")
print("="*70)

# ---- Extract Real "None" Samples from Test Set ----
print("\n📋 Extracting 'None' samples from test set...")
none_class_id = LABEL2ID_CANON["None"]
none_indices = np.where(y_test == none_class_id)[0]

np.random.seed(42)
if len(none_indices) >= 10:
    selected_none_indices = np.random.choice(none_indices, size=10, replace=False)
else:
    selected_none_indices = none_indices

NONE_SAMPLES = [X_test[i] for i in selected_none_indices]
print(f"✅ Selected {len(NONE_SAMPLES)} 'None' samples from test set")

# ---- Curated Reddit-Style Mental Health Samples (10 each) ----

DEPRESSION_SAMPLES = [
    "I can't remember the last time I felt genuinely happy. Everything just feels gray and pointless.",
    "Been in bed for 3 days straight. I know I should shower and eat but I just can't find the energy.",
    "I feel like I'm drowning and everyone around me is breathing just fine. Why is it so hard for me?",
    "Nothing brings me joy anymore. Not my hobbies, not my friends, nothing. I'm just going through the motions.",
    "I cry every single day and I don't even know why anymore. It's exhausting.",
    "My family tells me to 'just be happy' but they don't understand that I can't just snap out of this.",
    "Is it normal to feel empty all the time? Like there's a void inside that nothing can fill?",
    "I used to love painting but now I can't even pick up a brush. I've lost interest in everything.",
    "Sleeping 14 hours a day and still feeling exhausted. What's wrong with me?",
    "I canceled plans with friends again. I just can't bring myself to socialize anymore.",
]

BIPOLAR_SAMPLES = [
    "I haven't slept in 4 days and I feel AMAZING! So much energy! Started 3 new projects!",
    "Last week I was on top of the world, today I can't even get out of bed. This rollercoaster is killing me.",
    "My mind is racing so fast I can't keep up with my own thoughts. Is this normal?",
    "I spent $3000 on things I don't need during a manic episode and now I'm broke and depressed about it.",
    "One minute I'm euphoric and invincible, the next I'm crying on the floor. I hate this so much.",
    "I was so productive yesterday, worked 18 hours straight. Today I feel like I'm dying and everything seems pointless.",
    "My family says I'm 'too much' when I'm up and 'too distant' when I'm down. I can't win.",
    "The crash after a manic episode is the worst feeling. Going from feeling invincible to feeling worthless.",
    "I have so many unfinished projects from my manic phases. My room is full of half-done things.",
    "My mood swings are so extreme that I don't even recognize myself sometimes.",
]

PERSONALITY_DISORDER_SAMPLES = [
    "My boyfriend didn't text me back for 2 hours and now I'm convinced he hates me and wants to break up.",
    "I don't know who I am anymore. My personality seems to change depending on who I'm with.",
    "I go from loving someone to hating them in seconds. My emotions are so intense and unstable.",
    "I have this overwhelming fear of abandonment that controls my life. I push people away before they can leave me.",
    "I feel empty inside all the time. Like there's nothing at the core of who I am.",
    "My relationships are always intense and chaotic. I idealize people then suddenly see them as terrible.",
    "I have such an unstable sense of self. Yesterday I wanted to be a writer, today I want to drop everything.",
    "My mood can change drastically within hours. People say I'm unpredictable.",
    "I split on people constantly - they're either perfect or terrible, no in-between.",
    "I'm terrified of being alone but I also push everyone away. I don't understand myself.",
]

ANXIETY_SAMPLES = [
    "My heart is racing for no reason and I can't calm down. What if something bad is about to happen?",
    "I've been having panic attacks almost daily. My chest gets tight and I feel like I can't breathe.",
    "I'm so worried about everything all the time. What if I lose my job? What if I get sick?",
    "I had to leave the grocery store because I started having a panic attack. Too many people.",
    "I can't stop thinking about all the things that could go wrong. My mind won't shut off.",
    "I've been having intrusive thoughts that keep me up at night. The constant worry is exhausting.",
    "Social situations make me so anxious that I avoid them completely. I'm lonely but terrified of interaction.",
    "I replay conversations in my head over and over, analyzing every word I said. Did I say something wrong?",
    "I catastrophize everything. If my boss wants to talk to me, I immediately think I'm getting fired.",
    "I check the locks on my doors multiple times before bed because I'm anxious about safety.",
]

# ---- Combine All Samples ----
all_samples = []

for text in NONE_SAMPLES:
    all_samples.append({"text": text, "true_label": "None"})

for text in DEPRESSION_SAMPLES:
    all_samples.append({"text": text, "true_label": "Depression"})

for text in BIPOLAR_SAMPLES:
    all_samples.append({"text": text, "true_label": "Bipolar disorder"})

for text in PERSONALITY_DISORDER_SAMPLES:
    all_samples.append({"text": text, "true_label": "Personality disorder"})

for text in ANXIETY_SAMPLES:
    all_samples.append({"text": text, "true_label": "Anxiety"})

print(f"\n✅ Total samples loaded: {len(all_samples)}")
print(f"   - None: {len(NONE_SAMPLES)}")
print(f"   - Depression: {len(DEPRESSION_SAMPLES)}")
print(f"   - Bipolar disorder: {len(BIPOLAR_SAMPLES)}")
print(f"   - Personality Disorder: {len(PERSONALITY_DISORDER_SAMPLES)}")
print(f"   - Anxiety: {len(ANXIETY_SAMPLES)}")

# ---- Make Predictions on Hybrid Samples ----
print("\n🔮 Making predictions on all hybrid samples...")

texts = [s["text"] for s in all_samples]
true_labels = [s["true_label"] for s in all_samples]

# Tokenize
encodings = roberta_tokenizer(
    texts,
    padding=True,
    truncation=True,
    max_length=MAX_LENGTH,
    return_tensors="pt"
)

# Move to device and predict
encodings = {k: v.to(device) for k, v in encodings.items()}

with torch.no_grad():
    outputs = model_v1(**encodings)
    logits = outputs.logits
    pred_ids = torch.argmax(logits, dim=-1).cpu().numpy()

# Convert predictions to label names
pred_labels = [ID2LABEL_CANON[pred_id] for pred_id in pred_ids]

print("✅ Predictions complete!")

# ---- Create Visualization DataFrame ----
print("\n📊 Creating results dataframe...")

viz_data = []
for i, (text, true_label, pred_label) in enumerate(zip(texts, true_labels, pred_labels)):
    display_text = text[:300] + "..." if len(text) > 300 else text
    viz_data.append({
        "Sample_Num": i + 1,
        "True_Label": true_label,
        "Predicted_Label": pred_label,
        "Text": display_text,
        "Correct": true_label == pred_label,
        "Full_Text": text
    })

viz_df = pd.DataFrame(viz_data)
viz_df.to_csv("hybrid_sample_predictions.csv", index=False)
print(f"✅ Saved predictions to: hybrid_sample_predictions.csv")

# ---- VISUAL DISPLAY BY CLASS ----
print("\n" + "="*70)
print("DETAILED SAMPLE PREDICTIONS BY CLASS")
print("="*70)

class_order = ["None", "Depression", "Bipolar disorder", "Personality disorder", "Anxiety"]

for class_name in class_order:
    class_df = viz_df[viz_df["True_Label"] == class_name]

    if len(class_df) == 0:
        continue

    print(f"\n\n{'='*70}")
    print(f"{class_name} - Samples 1 to {len(class_df)} of {len(class_df)}")
    print('='*70)

    # Display each sample with visual styling
    html_output = f"<h2 style='color: #333; margin-bottom: 20px;'>{class_name} - Samples 1 to {len(class_df)} of {len(class_df)}</h2>"

    for idx, (_, row) in enumerate(class_df.iterrows(), 1):
        is_correct = row["Correct"]
        bg_color = "#e8f5e9" if is_correct else "#ffebee"
        border_color = "#4caf50" if is_correct else "#f44336"
        status = "✓ CORRECT" if is_correct else "✗ INCORRECT"
        status_color = "#2e7d32" if is_correct else "#c62828"

        html_output += f"""
        <div style='border: 3px solid {border_color}; border-radius: 8px; padding: 15px; margin-bottom: 15px; background-color: {bg_color};'>
            <div style='font-weight: bold; font-size: 14px; margin-bottom: 8px;'>
                Sample #{row["Sample_Num"]}
                <span style='float: right; color: {status_color}; font-weight: bold;'>{status}</span>
            </div>
            <div style='background-color: white; padding: 10px; border-radius: 4px; margin-bottom: 8px; font-size: 13px; line-height: 1.5;'>
                <strong>Text:</strong><br>
                {row["Text"]}
            </div>
            <div style='font-size: 12px;'>
                <div><strong style='color: #1565c0;'>True Label:</strong> {row["True_Label"]}</div>
                <div><strong style='color: #d84315;'>Predicted Label:</strong> {row["Predicted_Label"]}</div>
            </div>
        </div>
        """

    display(HTML(html_output))

# ---- Statistics by Class ----
print("\n" + "="*70)
print("PREDICTION STATISTICS BY CLASS")
print("="*70)

for class_name in class_order:
    class_df = viz_df[viz_df["True_Label"] == class_name]

    if len(class_df) == 0:
        continue

    correct = class_df["Correct"].sum()
    total = len(class_df)
    accuracy = (correct / total * 100) if total > 0 else 0

    print(f"\n{class_name}:")
    print(f"   Total samples: {total}")
    print(f"   Correct: {correct}/{total} ({accuracy:.1f}%)")

    if correct < total:
        wrong_df = class_df[~class_df["Correct"]]
        misclass_counts = wrong_df["Predicted_Label"].value_counts()
        if len(misclass_counts) > 0:
            print(f"   Common misclassifications:")
            for pred_label, count in misclass_counts.head(3).items():
                print(f"      → {pred_label}: {count} samples")

overall_acc = viz_df["Correct"].mean() * 100
print(f"\n📊 Overall accuracy on hybrid samples: {overall_acc:.1f}%")

# ---- Confusion Matrix ----
y_true = [LABEL2ID_CANON[label] for label in true_labels]
y_pred = pred_ids

cm = confusion_matrix(y_true, y_pred)
cm_percent = cm.astype("float") / cm.sum(axis=1)[:, np.newaxis] * 100

print("\n📊 Confusion Matrix (Percentages):")
print(cm_percent.round(1))

print("\n📊 Classification Report:")
report = classification_report(
    y_true,
    y_pred,
    target_names=class_order,
    digits=4
)
print(report)

# ---- Summary Table ----
print("\n" + "="*70)
print("FINAL SUMMARY TABLE")
print("="*70)

summary_data = []
for class_name in class_order:
    class_df = viz_df[viz_df["True_Label"] == class_name]

    if len(class_df) == 0:
        continue

    correct = class_df["Correct"].sum()
    total = len(class_df)
    accuracy = (correct / total * 100) if total > 0 else 0

    summary_data.append({
        "Class": class_name,
        "Total Samples": total,
        "Correct": correct,
        "Incorrect": total - correct,
        "Accuracy (%)": f"{accuracy:.1f}"
    })

summary_df = pd.DataFrame(summary_data)
print("\n" + summary_df.to_string(index=False))

print("\n" + "="*70)
print("HYBRID SAMPLE TESTING COMPLETE!")
print("="*70)
print(f"\n📁 CSV file saved: hybrid_sample_predictions.csv")
print(f"📊 Total samples tested: {len(viz_df)}")
print(f"🎯 Overall accuracy: {overall_acc:.1f}%")
print(f"🏆 Model tested: Version 1 (General RoBERTa-base)")



















# ============================================================
# CELL 1: Install and Import Dependencies
# ============================================================
# Run this FIRST in a fresh Colab runtime
!pip install -q transformers torch scikit-learn pandas matplotlib numpy

import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"  # Use GPU 0

import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
from sklearn.metrics import classification_report, confusion_matrix
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from datasets import Dataset

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"Device: {torch.device('cuda' if torch.cuda.is_available() else 'cpu')}")

# ============================================================
# CELL 2: Hugging Face Login (OPTIONAL - only if model needs it)
# ============================================================
# Uncomment if you need to access gated models
# from huggingface_hub import login
# login()  # This will prompt for your token

# ============================================================
# CELL 3: Version 2 – MentalRoBERTa Fine-tuning
# ============================================================
# Assuming you have: train_loader, val_loader, test_loader, id2label_hf, label2id_hf, ID2LABEL_CANON

SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

label_list = [id2label_hf[i] for i in range(len(id2label_hf))]
print("=== Version 2: MentalRoBERTa ===")

# Load MentalRoBERTa (try to access, if fails use roberta-base as fallback)
try:
    MODEL_NAME = "mental/mental-roberta-base"
    print(f"Attempting to load: {MODEL_NAME}")
    tokenizer_v2 = AutoTokenizer.from_pretrained(MODEL_NAME)
    model_v2 = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=len(id2label_hf),
        id2label=id2label_hf,
        label2id=label2id_hf,
    )
    print(f"Successfully loaded {MODEL_NAME}")
except Exception as e:
    print(f"Could not load MentalRoBERTa: {e}")
    print("Falling back to roberta-base...")
    MODEL_NAME = "roberta-base"
    tokenizer_v2 = AutoTokenizer.from_pretrained(MODEL_NAME)
    model_v2 = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=len(id2label_hf),
        id2label=id2label_hf,
        label2id=label2id_hf,
    )
    print(f"Loaded {MODEL_NAME}")

# ============================================================
# CELL 4: Training Arguments
# ============================================================
os.environ["WANDB_DISABLED"] = "true"  # Disable wandb logging

training_args = TrainingArguments(
    output_dir="./results_v2",
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir="./logs_v2",
    logging_steps=100,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    learning_rate=2e-5,
    seed=SEED,
    report_to=[],  # Don't report to any service
)

# ============================================================
# CELL 5: Create Trainer and Train
# ============================================================
trainer = Trainer(
    model=model_v2,
    args=training_args,
    train_dataset=train_dataset,  # Assuming you have this as a Hugging Face Dataset
    eval_dataset=val_dataset,      # Assuming you have this as a Hugging Face Dataset
)

print("Starting training...")
trainer.train()
print("Training complete!")

# ============================================================
# CELL 6: Evaluate on Test Set
# ============================================================
print("\n--- Test Evaluation ---")
test_results = trainer.evaluate(test_dataset)  # Assuming you have this as a Hugging Face Dataset
print(test_results)

# ============================================================
# CELL 7: Generate Predictions and Metrics
# ============================================================
predictions = trainer.predict(test_dataset)
pred_labels = np.argmax(predictions.predictions, axis=1)

# Extract true labels from custom dataset
true_labels = np.array([test_dataset[i][1] for i in range(len(test_dataset))])

report_v2 = classification_report(
    true_labels,
    pred_labels,
    output_dict=True,
    zero_division=0
)

classes_order = [0, 1, 2, 3, 4]

# Extract metrics
metrics_data_v2 = {
    "Class": [ID2LABEL_CANON[i] for i in classes_order],
    "Precision": [report_v2[str(i)]["precision"] for i in classes_order],
    "Recall": [report_v2[str(i)]["recall"] for i in classes_order],
    "F1": [report_v2[str(i)]["f1-score"] for i in classes_order],
}

metrics_df_v2 = pd.DataFrame(metrics_data_v2)

# Calculate per-class accuracy
accuracy_per_class_v2 = []
for i in classes_order:
    class_mask = true_labels == i
    if class_mask.sum() > 0:
        correct = (true_labels[class_mask] == pred_labels[class_mask]).sum()
        accuracy = correct / class_mask.sum()
    else:
        accuracy = 0
    accuracy_per_class_v2.append(accuracy)

metrics_df_v2["Accuracy"] = accuracy_per_class_v2

print("\nClass-wise Metrics Summary – Version 2 (MentalRoBERTa)")
print(metrics_df_v2)

# ============================================================
# CELL 8: Visualizations
# ============================================================
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle("Class-wise Performance Metrics – Version 2 (MentalRoBERTa)", fontsize=14, fontweight="bold")

metrics = ["Precision", "Recall", "F1", "Accuracy"]
colors = ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728"]

for idx, (ax, metric, color) in enumerate(zip(axes.flat, metrics, colors)):
    values = metrics_df_v2[metric].values
    max_val = values.max()

    bar_colors = [color if v == max_val else "#cccccc" for v in values]

    ax.bar(metrics_df_v2["Class"], values, color=bar_colors, edgecolor="black", linewidth=1.5)
    ax.set_ylabel(metric, fontsize=11, fontweight="bold")
    ax.set_title(f"{metric} by Class", fontsize=12, fontweight="bold")
    ax.set_ylim(0, 1.0)
    ax.grid(axis="y", alpha=0.3)
    ax.tick_params(axis="x", rotation=45)

plt.tight_layout()
plt.show()

display(metrics_df_v2)

